# Generated by Django 5.2.4 on 2025-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_producto_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
