# Generated by Django 5.2.4 on 2025-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detallepedido_con_borde_pedido_observacion_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ind_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('local', 'En el local'), ('delivery', 'Delivery o Retiro')], default='local', max_length=20),
        ),
    ]
