# Generated by Django 5.2.4 on 2025-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_ind_bancario_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_ventas', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
    ]
