# Generated by Django 5.2.4 on 2025-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('local', 'En el local'), ('delivery', 'Delivery'), ('retiro', 'Retiro')], default='local', max_length=20),
        ),
    ]
