# Generated by Django 5.2.4 on 2025-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cierre_caja', models.CharField(blank=True, max_length=100, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_final',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_gastos',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
