# Generated by Django 5.2.4 on 2025-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_cierrecaja_total_final_cierrecaja_total_gastos_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierrecaja',
            old_name='total_final',
            new_name='saldo_actual',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
