# Generated by Django 5.2.4 on 2025-10-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_gasto_cierrecaja_total_final_cierrecaja_total_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cierrecaja'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
