# Generated by Django 5.2.7 on 2025-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_gasto_cierre_caja_alter_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierrecaja',
            old_name='total_final',
            new_name='saldo_actual',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
