# Generated by Django 5.2.4 on 2025-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_rename_total_final_cierrecaja_saldo_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_bancario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_bancario_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_efectivo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='saldo_efectivo_anterior',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gasto',
            name='ind_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('hamburguesa', 'Hamburguesa'), ('papas', 'Papas'), ('bebida', 'Bebida'), ('menu', 'Menú'), ('otro', 'Otro')], max_length=20),
        ),
    ]
