# Generated by Django 5.2.4 on 2025-12-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_cierrecaja_saldo_bancario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('imagen', models.ImageField(upload_to='menus_diarios/')),
            ],
        ),
    ]
