# Generated by Django 5.2.4 on 2025-12-22 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_menudiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
