# Generated by Django 5.2.4 on 2026-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_menudiario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='condicion_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=20),
        ),
    ]
